# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6591f7feb09672d9fd1116e874b9e137a98574e27e15cc37bf80ae90a5f3f6d5c18207b6f4219840d36f2569fadfaef6f75627305e1dd6d1dce517b7f6be0a47

test:
  secret_key_base: d01240bb48df091213cfad5cf829ad6eb9715c98733cc54774fa52be698305b2e5652d905ef3d009b3dcdc502de1440888a34f462bcd1f17a73f3a0ba622ef5e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
